### PR TITLE
dist: add Dockerfile

### PR DESCRIPTION
**Pull request by lucab**
This adds a multi-stage Dockerfile, with an alpine-3.9 run environment.

### CODE REVIEW

**Comment by lucab** [comment]
@arithx this should be the last PR for this batch. I plan to set up a container auto-builder on quay.io after this.

**Comment by lucab** [comment]
@arithx yes, I plan to have a docker/podman/rkt/whatever command example once the quay repository is up and contentful.

Regarding travis, do you have in mind a `docker build` run (to make sure the container image can be build) or is that something different?

**Comment by arithx** [comment]
Yeah, I was envisioning just a simple `docker build`

**Comment by lucab** [comment]
@arithx ack, pushed an additional commit on top for that. Travis seems happy.

**Comment by lucab** [comment]
Set up https://quay.io/repository/coreos/airlock?tab=tags with triggered autobuilding (and tested trigger).

**Pull request merged**
