### PR TITLE
airlock: add logging

### PR DESCRIPTION
**Pull request by lucab**

### CODE REVIEW

**Comment by lucab** [comment]
@arithx this seemed straightforward and travis is happy. If you have a few spare seconds, I won't mind a quick sanity check.

**Comment by lucab** [comment]
@arithx Ack, thanks. Do we need/want to keep `vendor/`? My understanding is that it is mostly meant for compatibility, but I'm starting with 1.11 as baseline here.

**Comment by arithx** [comment]
It's not strictly necessary to carry it anymore (and is ignored by `go build` without the `-mod=vendor` flag). The one thing I could think of would be to have the direct code of the dependencies used to build releases included into the repository (rather than just the hash). If we don't end up including it we'll want to make sure that we add `go mod verify` into the `Makefile` / build script.

**Comment by lucab** [comment]
@arithx I ended up adding `vendor/` and massaging travis to use that. Thanks again for all your feedback!

**Pull request merged**
